connector.name=hive
hive.metastore.uri=thrift://hive-metastore:9083

# Enable HDFS file system support
fs.hadoop.enabled=true
hive.config.resources=/etc/trino/core-site.xml,/etc/trino/hdfs-site.xml

# Allow reading files without registered tables
hive.allow-register-partition-procedure=true
hive.non-managed-table-writes-enabled=true
