version: '3.8'

services:
  # PostgreSQL для Hive Metastore
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hivepassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Hadoop HDFS NameNode
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    environment:
      - CLUSTER_NAME=test-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    ports:
      - "9870:9870" # Web UI
      - "9000:9000" # HDFS port
    volumes:
      - namenode_data:/hadoop/dfs/name

  # Hadoop HDFS DataNode
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    depends_on:
      - namenode
    ports:
      - "9864:9864" # Web UI
    volumes:
      - datanode_data:/hadoop/dfs/data

  # Hive Metastore
  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    restart: always
    depends_on:
      - postgres
      - namenode
    environment:
      HIVE_METASTORE_URI: thrift://hive-metastore:9083
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hivepassword
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
    ports:
      - "9083:9083"

  # Trino
  trino:
    image: trinodb/trino:423
    container_name: trino
    restart: always
    depends_on:
      - hive-metastore
    ports:
      - "8081:8080" # Web UI на 8081 хоста
    volumes:
      - ./trino/etc:/etc/trino
      - ./trino/data:/var/trino/data

  # Spark
  spark:
    image: bitnami/spark:3
    container_name: spark
    restart: always
    depends_on:
      - namenode
    environment:
      - SPARK_MODE=master
      - SPARK_LOCAL_IP=spark
      - SPARK_MASTER_URL=spark://spark:7077
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    ports:
      - "8080:8080" # Spark Master UI
      - "7077:7077"
    volumes:
      - spark_data:/bitnami/spark

  airflow:
    image: apache/airflow:2.7.0
    container_name: airflow
    restart: always
    depends_on:
      - spark
      - hive-metastore
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://hive:hivepassword@postgres:5432/metastore
    ports:
      - "8082:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    command: webserver


volumes:
  postgres_data:
  namenode_data:
  datanode_data:
  spark_data:
