"""#1472: match parsing stays byte-identical to master and fast.

The golden file was generated by the parser of the base commit (before the
``schema_fingerprint`` hoist) from three real WhoScored match pages.
"""

from __future__ import annotations

import gzip
import hashlib
import json
import time
from pathlib import Path

import pytest

from scrapers.whoscored.domain import WhoScoredScope
from scrapers.whoscored.parsers import parse_match_html

FIXTURES = Path(__file__).resolve().parents[2] / "fixtures" / "whoscored"
GOLDEN = json.loads((FIXTURES / "match_golden.json").read_text(encoding="utf-8"))
SCOPE = WhoScoredScope("WS-test", "2526", "split_year")


def _html(game_id: int) -> str:
    with gzip.open(FIXTURES / f"match-{game_id}.raw.gz", "rt", encoding="utf-8") as handle:
        return handle.read()


def _digest(rows) -> str:
    digest = hashlib.sha256()
    for row in rows:
        digest.update(json.dumps(row, sort_keys=True, default=str).encode("utf-8"))
        digest.update(b"\n")
    return digest.hexdigest()


@pytest.mark.parametrize("game_id", [1952492, 1946345, 1955749])
def test_match_datasets_equal_master_golden(game_id):
    result = parse_match_html(_html(game_id), scope=SCOPE, game_id=game_id)

    actual = {
        name: {"rows": len(dataset.rows), "sha256": _digest(dataset.rows)}
        for name, dataset in result.datasets.items()
    }

    assert len(actual) == 7
    assert actual == GOLDEN[str(game_id)]


def test_heaviest_match_parses_under_two_seconds():
    html = _html(1952492)

    started = time.perf_counter()
    parse_match_html(html, scope=SCOPE, game_id=1952492)
    elapsed = time.perf_counter() - started

    assert elapsed < 2.0, f"match-1952492 parsed in {elapsed:.2f}s"
