from __future__ import annotations

import json

import pytest

from scripts.verify_fbref_acceptance_image import (
    AcceptanceImageError,
    SOURCE_DIRECTORIES,
    verify_manifest,
    write_manifest,
)


GIT_SHA = "a" * 40
GIT_TREE = "b" * 40
SOURCE_SHA = "c" * 64
IMAGE_ID = "sha256:" + "d" * 64


def _source_tree(tmp_path):
    root = tmp_path / "airflow"
    for directory in SOURCE_DIRECTORIES:
        path = root / directory
        path.mkdir(parents=True)
        (path / f"{directory}.txt").write_text(
            f"exact {directory}\n",
            encoding="utf-8",
        )
    return root


def _environment(**changes):
    values = {
        "GIT_SHA": GIT_SHA,
        "FBREF_EXPECTED_GIT_SHA": GIT_SHA,
        "FBREF_ACCEPTANCE_SOURCE_SHA256": SOURCE_SHA,
        "FBREF_EXPECTED_IMAGE_DIGEST": IMAGE_ID,
        "FBREF_IMAGE_DIGEST": IMAGE_ID,
    }
    values.update(changes)
    return values


def _sealed_tree(tmp_path):
    root = _source_tree(tmp_path)
    manifest = tmp_path / "manifest.json"
    write_manifest(
        manifest,
        source_root=root,
        git_sha=GIT_SHA,
        git_tree=GIT_TREE,
        source_archive_sha256=SOURCE_SHA,
    )
    return root, manifest


def test_exact_baked_tree_and_operator_provenance_pass(tmp_path):
    root, manifest = _sealed_tree(tmp_path)

    result = verify_manifest(
        manifest,
        source_root=root,
        environment=_environment(),
    )

    assert result["status"] == "passed"
    assert result["git_sha"] == GIT_SHA
    assert result["git_tree"] == GIT_TREE
    assert result["image_digest"] == IMAGE_ID


@pytest.mark.parametrize(
    "changes",
    [
        {"FBREF_EXPECTED_GIT_SHA": "e" * 40},
        {"FBREF_EXPECTED_IMAGE_DIGEST": "mutable:tag"},
        {"FBREF_IMAGE_DIGEST": "sha256:" + "e" * 64},
        {"FBREF_ACCEPTANCE_SOURCE_SHA256": "f" * 64},
    ],
)
def test_operator_or_baked_provenance_mismatch_fails_closed(tmp_path, changes):
    root, manifest = _sealed_tree(tmp_path)

    with pytest.raises(AcceptanceImageError):
        verify_manifest(
            manifest,
            source_root=root,
            environment=_environment(**changes),
        )


def test_runtime_source_change_fails_closed(tmp_path):
    root, manifest = _sealed_tree(tmp_path)
    (root / "scrapers" / "scrapers.txt").write_text(
        "mutated after build\n",
        encoding="utf-8",
    )

    with pytest.raises(AcceptanceImageError, match="baked source tree differs"):
        verify_manifest(
            manifest,
            source_root=root,
            environment=_environment(),
        )


def test_runtime_extra_source_file_fails_closed(tmp_path):
    root, manifest = _sealed_tree(tmp_path)
    (root / "dags" / "unexpected.py").write_text("pass\n", encoding="utf-8")

    with pytest.raises(AcceptanceImageError, match="baked source tree differs"):
        verify_manifest(
            manifest,
            source_root=root,
            environment=_environment(),
        )


def test_generated_bytecode_fails_closed(tmp_path):
    root, manifest = _sealed_tree(tmp_path)
    bytecode = root / "scripts" / "__pycache__"
    bytecode.mkdir()
    (bytecode / "tampered.pyc").write_bytes(b"not source")

    with pytest.raises(
        AcceptanceImageError, match="generated bytecode"
    ):
        verify_manifest(
            manifest,
            source_root=root,
            environment=_environment(),
        )


def test_missing_runtime_source_directory_fails_closed(tmp_path):
    root, manifest = _sealed_tree(tmp_path)
    (root / "configs").rename(root / "configs-missing")

    with pytest.raises(AcceptanceImageError, match="source directory is missing"):
        verify_manifest(
            manifest,
            source_root=root,
            environment=_environment(),
        )


def test_manifest_contains_no_secret_environment_values(tmp_path):
    _, manifest = _sealed_tree(tmp_path)

    payload = json.loads(manifest.read_text(encoding="ascii"))

    assert set(payload) == {
        "schema_version",
        "git_sha",
        "git_tree",
        "source_archive_sha256",
        "source_tree_sha256",
        "files",
    }
