# =============================================================================
# Trino Logging Configuration
# =============================================================================

io.trino=INFO
