#!/usr/bin/env python3
"""Verify immutable source/image provenance for FBref acceptance containers."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import stat
from pathlib import Path
from typing import Iterable, Mapping


SOURCE_DIRECTORIES = ("dags", "scrapers", "scripts", "configs")
DEFAULT_SOURCE_ROOT = Path("/opt/airflow")
DEFAULT_MANIFEST = Path(
    "/opt/airflow/runtime-contract/fbref-acceptance/source-manifest.json"
)
_HEX_40 = re.compile(r"[0-9a-f]{40}")
_HEX_64 = re.compile(r"[0-9a-f]{64}")
_IMAGE_ID = re.compile(r"sha256:[0-9a-f]{64}")


class AcceptanceImageError(RuntimeError):
    """The acceptance image does not match its immutable declaration."""


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        while chunk := stream.read(1024 * 1024):
            digest.update(chunk)
    return digest.hexdigest()


def _ignored(path: Path) -> bool:
    # Generated bytecode is loadable code, not harmless build noise.  The
    # acceptance image sets PYTHONDONTWRITEBYTECODE, so any such file means
    # the sealed source tree was changed after image creation.
    return False


def source_records(
    source_root: Path,
    directories: Iterable[str] = SOURCE_DIRECTORIES,
) -> list[dict[str, object]]:
    """Hash the complete baked runtime tree, rejecting escaping symlinks."""

    root = source_root.resolve()
    records: list[dict[str, object]] = []
    for directory in directories:
        candidate = root / directory
        if candidate.is_symlink():
            raise AcceptanceImageError(
                f"FBref acceptance source directory is a symlink: {directory}"
            )
        if not candidate.is_dir():
            raise AcceptanceImageError(
                f"FBref acceptance source directory is missing: {directory}"
            )
        for path in sorted(candidate.rglob("*")):
            relative = path.relative_to(root)
            if _ignored(relative):
                continue
            if path.is_symlink():
                raise AcceptanceImageError(
                    f"FBref acceptance source contains a symlink: {relative}"
                )
            if "__pycache__" in relative.parts or path.suffix in {".pyc", ".pyo"}:
                raise AcceptanceImageError(
                    f"FBref acceptance source contains generated bytecode: {relative}"
                )
            if not path.is_file():
                continue
            records.append(
                {
                    "path": relative.as_posix(),
                    "mode": stat.S_IMODE(path.stat().st_mode),
                    "sha256": _sha256(path),
                }
            )
    if not records:
        raise AcceptanceImageError("FBref acceptance source tree is empty")
    return records


def _records_sha256(records: list[dict[str, object]]) -> str:
    payload = json.dumps(
        records,
        ensure_ascii=True,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("ascii")
    return hashlib.sha256(payload).hexdigest()


def write_manifest(
    manifest_path: Path,
    *,
    source_root: Path,
    git_sha: str,
    git_tree: str,
    source_archive_sha256: str,
) -> Mapping[str, object]:
    """Seal the exact git-archive payload while the image layer is built."""

    if not _HEX_40.fullmatch(git_sha):
        raise AcceptanceImageError("FBref acceptance Git SHA must be full SHA-1")
    if not _HEX_40.fullmatch(git_tree):
        raise AcceptanceImageError("FBref acceptance Git tree must be full SHA-1")
    if not _HEX_64.fullmatch(source_archive_sha256):
        raise AcceptanceImageError(
            "FBref acceptance source archive must have a SHA-256"
        )
    records = source_records(source_root)
    payload: dict[str, object] = {
        "schema_version": 1,
        "git_sha": git_sha,
        "git_tree": git_tree,
        "source_archive_sha256": source_archive_sha256,
        "source_tree_sha256": _records_sha256(records),
        "files": records,
    }
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(
        json.dumps(payload, ensure_ascii=True, separators=(",", ":"), sort_keys=True)
        + "\n",
        encoding="ascii",
    )
    return payload


def verify_manifest(
    manifest_path: Path = DEFAULT_MANIFEST,
    *,
    source_root: Path = DEFAULT_SOURCE_ROOT,
    environment: Mapping[str, str] | None = None,
) -> Mapping[str, object]:
    """Fail closed before Airflow/proxy imports when provenance differs."""

    env = os.environ if environment is None else environment
    try:
        manifest = json.loads(manifest_path.read_text(encoding="ascii"))
    except Exception as exc:
        raise AcceptanceImageError(
            "FBref acceptance source manifest is unavailable"
        ) from exc
    if not isinstance(manifest, Mapping) or manifest.get("schema_version") != 1:
        raise AcceptanceImageError("FBref acceptance source manifest is invalid")

    baked_git_sha = str(env.get("GIT_SHA") or "").strip().lower()
    expected_git_sha = str(env.get("FBREF_EXPECTED_GIT_SHA") or "").strip().lower()
    if (
        not _HEX_40.fullmatch(baked_git_sha)
        or expected_git_sha != baked_git_sha
        or manifest.get("git_sha") != baked_git_sha
    ):
        raise AcceptanceImageError("FBref acceptance Git provenance differs")

    baked_archive = str(
        env.get("FBREF_ACCEPTANCE_SOURCE_SHA256") or ""
    ).strip().lower()
    if (
        not _HEX_64.fullmatch(baked_archive)
        or manifest.get("source_archive_sha256") != baked_archive
    ):
        raise AcceptanceImageError("FBref acceptance source archive differs")

    expected_image = str(
        env.get("FBREF_EXPECTED_IMAGE_DIGEST") or ""
    ).strip().lower()
    report_image = str(env.get("FBREF_IMAGE_DIGEST") or "").strip().lower()
    if not _IMAGE_ID.fullmatch(expected_image) or report_image != expected_image:
        raise AcceptanceImageError("FBref acceptance image digest differs")

    records = source_records(source_root)
    if manifest.get("files") != records or manifest.get(
        "source_tree_sha256"
    ) != _records_sha256(records):
        raise AcceptanceImageError("FBref acceptance baked source tree differs")
    return {
        "status": "passed",
        "git_sha": baked_git_sha,
        "git_tree": str(manifest.get("git_tree") or ""),
        "image_digest": expected_image,
        "source_archive_sha256": baked_archive,
        "source_tree_sha256": str(manifest["source_tree_sha256"]),
    }


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--source-root", type=Path, default=DEFAULT_SOURCE_ROOT)
    parser.add_argument("--write-manifest", action="store_true")
    parser.add_argument("--git-sha")
    parser.add_argument("--git-tree")
    parser.add_argument("--source-archive-sha256")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    if args.write_manifest:
        result = write_manifest(
            args.manifest,
            source_root=args.source_root,
            git_sha=str(args.git_sha or ""),
            git_tree=str(args.git_tree or ""),
            source_archive_sha256=str(args.source_archive_sha256 or ""),
        )
        output = {
            key: result[key]
            for key in (
                "git_sha",
                "git_tree",
                "source_archive_sha256",
                "source_tree_sha256",
            )
        }
    else:
        output = verify_manifest(
            args.manifest,
            source_root=args.source_root,
        )
    print(json.dumps(output, ensure_ascii=True, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
